In [1]:
from pytorch_lightning.loggers import WandbLogger
from engine import Ctok
from STIMDataset import LabellingStrategy, STIMDataset
from model import Model
from pytorch_lightning import Trainer

In [2]:
import wandb
wandb.login()

wandb: Currently logged in as: iamkucuk (use `wandb login --relogin` to force relogin)


True

In [ ]:
model = Model()
dataset = STIMDataset(csv_file = "SPY_ta.csv", label_method=LabellingStrategy.zigzag, strategy_kwargs={"up_thresh":.05, "down_thresh":-.05})
engine = Ctok(model=model, dataset=dataset, learning_rate=1, batch_size=1024)
tb_logger = WandbLogger(project="cnn-ta")
trainer = Trainer(
    logger=tb_logger,
    benchmark=True,
    num_sanity_val_steps=0,
    reload_dataloaders_every_epoch=True,
    max_epochs=70
)
trainer.fit(engine)

GPU available: True, used: False
TPU available: None, using: 0 TPU cores


953
253


C:\Users\Furkan\miniconda3\envs\finance\lib\site-packages\pytorch_lightning\utilities\distributed.py:50: UserWarning: GPU available but not used. Set the --gpus flag when calling the script.
  warnings.warn(*args, **kwargs)
wandb: wandb version 0.10.26 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade



  | Name  | Type            | Params
------------------------------------------
0 | model | Model           | 23.6 K
1 | cf    | ConfusionMatrix | 0     
------------------------------------------
23.6 K    Trainable params
0         Non-trainable params
23.6 K    Total params
0.094     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

tensor([[1.0000, 0.0000, 0.0000],
        [0.3333, 0.6667, 0.0000],
        [0.8444, 0.1556, 0.0000]])
tensor(1.6667)


Validating: 0it [00:00, ?it/s]

tensor([[0.7692, 0.0769, 0.1538],
        [0.0000, 0.8000, 0.2000],
        [0.4889, 0.2533, 0.2578]])
tensor(1.8270)


Validating: 0it [00:00, ?it/s]

tensor([[0.9231, 0.0769, 0.0000],
        [0.1333, 0.8667, 0.0000],
        [0.7422, 0.2578, 0.0000]])
tensor(1.7897)


Validating: 0it [00:00, ?it/s]

tensor([[0.0000, 0.0000, 1.0000],
        [0.0000, 0.5333, 0.4667],
        [0.0000, 0.1111, 0.8889]])
tensor(1.4222)


Validating: 0it [00:00, ?it/s]

In [ ]:
from torch.utils.data.dataloader import DataLoader

dataset_test = STIMDataset(csv_file="SPY_ta.csv")#label_method=LabellingStrategy.zigzag, strategy_kwargs={"up_thresh":.05, "down_thresh":-.05})
dataset_test.transform_to_test()
test_loader = DataLoader(dataset=dataset_test, batch_size=1, shuffle=False)
trainer.test(engine, test_loader)

In [ ]:
engine.

In [ ]:
dataset.show_labeled_data()